### PR TITLE
Add Service Counters

### PR DESCRIPTION
**Pull request by cooperlees**
- Add handy per unit counters
  - Refer to README changes to see counters
- Service name needs to be added into `[Service]` config section to enable
- Add how to code gen into Development section of README
- Update docs with new config + JSON output

Test:

- Ensure tests stay passing
- Adjust fixtures + tests to incorporate 15 new keys for 1 service
- Run locally and see stats for chronyd + sshd
  - `cargo run -- -c monitord.conf -vv`
```json
{
  "monitord.services.chronyd.service.active_enter_timestamp": 1683556542382710,
  "monitord.services.chronyd.service.active_exit_timestamp": 0,
  "monitord.services.chronyd.service.cpuusage_nsec": 328951000,
  "monitord.services.chronyd.service.inactive_exit_timestamp": 1683556541360626,
  "monitord.services.chronyd.service.ioread_bytes": 18446744073709551615,
  "monitord.services.chronyd.service.ioread_operations": 18446744073709551615,
  "monitord.services.chronyd.service.memory_available": 18446744073709551615,
  "monitord.services.chronyd.service.memory_current": 5214208,
  "monitord.services.chronyd.service.nrestarts": 0,
  "monitord.services.chronyd.service.restart_usec": 100000,
  "monitord.services.chronyd.service.state_change_timestamp": 1683556542382710,
  "monitord.services.chronyd.service.status_errno": 0,
  "monitord.services.chronyd.service.tasks_current": 1,
  "monitord.services.chronyd.service.timeout_clean_usec": 18446744073709551615,
  "monitord.services.chronyd.service.watchdog_usec": 0,
  "monitord.services.sshd.service.active_enter_timestamp": 1683556543537641,
  "monitord.services.sshd.service.active_exit_timestamp": 0,
  "monitord.services.sshd.service.cpuusage_nsec": 34009000,
  "monitord.services.sshd.service.inactive_exit_timestamp": 1683556543429574,
  "monitord.services.sshd.service.ioread_bytes": 18446744073709551615,
  "monitord.services.sshd.service.ioread_operations": 18446744073709551615,
  "monitord.services.sshd.service.memory_available": 18446744073709551615,
  "monitord.services.sshd.service.memory_current": 2338816,
  "monitord.services.sshd.service.nrestarts": 0,
  "monitord.services.sshd.service.restart_usec": 42000000,
  "monitord.services.sshd.service.state_change_timestamp": 1683556543537641,
  "monitord.services.sshd.service.status_errno": 0,
  "monitord.services.sshd.service.tasks_current": 1,
  "monitord.services.sshd.service.timeout_clean_usec": 18446744073709551615,
  "monitord.services.sshd.service.watchdog_usec": 0,
}
```

### CODE REVIEW

**Comment by cooperlees** [comment]
@pallotron Any particular metrics you need I didn't include here?

I was thinking the math needed for uptime / downtime we can do in metald or add utility functions here if wanted but for now I am just pulling the raw systemd metrics.

**Comment by pallotron** [comment]
Thanks for working on this @cooperlees (🍕🍕🍕🍕🍕)

> Any particular metrics you need I didn't include here?

I think that all we need according to what that `sv_service_reporter.py` thing does in FBOSS.
Maybe `systemd` exposes some info about resource utilisation like FDs, threads? If not that's fine.

>  I was thinking the math needed for uptime / downtime we can do in metald/ODS or add utility functions here if wanted but for now I am just pulling the raw systemd metrics.

I think it can be done on the consumer side, don't worry about adding function here, just expose the raw data in this PR/`monitord`

**Comment by echistyakov** [comment]
Looks good, thank you for adding this.

`18446744073709551615` looks a little odd - should these metric use signed integers and display -1 instead?

**Comment by pallotron** [comment]
according to https://dbus.freedesktop.org/doc/dbus-specification.html#id-1.3.8

UINT64	116 (ASCII 't')	64-bit unsigned integer

maybe it's a problem of endianness?

**Comment by cooperlees** [comment]
> according to https://dbus.freedesktop.org/doc/dbus-specification.html#id-1.3.8
> 
> UINT64 116 (ASCII 't') 64-bit unsigned integer
> 
> maybe it's a problem of endianness?

Yeah no idea here - I'm going to merge this and fix the 1 i32 to represent correctly in json-flat in a dedicated PR as I'm going to have to make an enum of types and support JSON'ing that correctly for the `json-flat` (fbagent) format.

**Pull request merged**
